export const TABS = {
    chat:{
        title:'聊天',
        imgUrl:require('../image/chat.png')
    },
    contact:{
        title:'通讯录',
        imgUrl:require('../image/contact.png')
    },
    find:{
        title:'发现',
        imgUrl:require('../image/find.png')
    },
    mine:{
        title:'我的',
        imgUrl:require('../image/mine.png')
    },
}
export const API = {
    color:{
        dark:'#999',
        active:'green',
    }
}

//可滑动的菜单
export const MENU = [
    [
        {
            title:"京东超市",
            imgurl:require('../image/menu/jdcs.png')
        },
        {
            title:" 全球购",
            imgurl:require('../image/menu/qqg.png')
        },
        {
            title:"服装城",
            imgurl:require('../image/menu/fzc.png')
        },
        {
            title:"京东生鲜",
            imgurl:require('../image/menu/jdsx.png')
        },
        {
            title:"京东到家",
            imgurl:require('../image/menu/jddj.png')
        },
        {
            title:"充值缴费",
            imgurl:require('../image/menu/czjf.png')
        },
        {
            title:"领京豆",
            imgurl:require('../image/menu/ljd.png')
        },
        {
            title:"领券",
            imgurl:require('../image/menu/lq.png')
        },
        {
            title:"惠赚钱",
            imgurl:require('../image/menu/hzq.png')
        },
        {
            title:"物流查询",
            imgurl:require('../image/menu/wlcx.png')
        }
    ],
    [
        {
            title:"新品T恤",
            imgurl:require('../image/menu/xptx.jpg')
        },
        {
            title:"POLO衫",
            imgurl:require('../image/menu/popls.jpg')
        },
        {
            title:"牛仔裤",
            imgurl:require('../image/menu/nzk.jpg')
        },
        {
            title:"休闲裤",
            imgurl:require('../image/menu/xxk.jpg')
        },
        {
            title:"短裤",
            imgurl:require('../image/menu/dk.jpg')
        },
        {
            title:"夹克",
            imgurl:require('../image/menu/jk.jpg')
        },
        {
            title:"休闲",
            imgurl:require('../image/menu/xf.jpg')
        },
        {
            title:"自营男装",
            imgurl:require('../image/menu/zynz.jpg')
        },
        {
            title:"新款T恤",
            imgurl:require('../image/menu/xktx.jpg')
        },
        {
            title:"精品衬衫",
            imgurl:require('../image/menu/jpcs.jpg')
        }
    ]
]
